# https://endler.dev/2020/rust-compile-times/#switch-to-a-faster-linker
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

# https://github.com/rust-analyzer/rust-analyzer/blob/master/.cargo/config
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
